# Generated by Django 6.1.1 on 2026-09-28 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('lab', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, db_index=True, max_length=30, unique=True)),
                ('consultation_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('lab_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('medicine_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('other_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partially Paid'), ('paid', 'Fully Paid'), ('refunded', 'Refunded')], db_index=True, default='unpaid', max_length=20)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash Payment'), ('upi', 'UPI / QR Code / GPay / PhonePe'), ('card', 'Credit / Debit Card (POS)'), ('net_banking', 'Net Banking / IMPS / NEFT')], default='cash', max_length=20)),
                ('transaction_reference', models.CharField(blank=True, help_text='UPI Ref ID / Card Txn ID', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='appointments.appointment')),
                ('lab_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='lab.laborder')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='patients.patient')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at', 'payment_status'], name='billing_inv_created_b9b144_idx'), models.Index(fields=['payment_method'], name='billing_inv_payment_c82b6a_idx')],
            },
        ),
    ]
