# Generated by Django 6.1.1 on 2026-09-28 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField(help_text='Primary and differential diagnosis')),
                ('chief_complaints', models.TextField(blank=True, help_text='Patient reported symptoms')),
                ('blood_pressure', models.CharField(blank=True, help_text='e.g. 120/80 mmHg', max_length=20)),
                ('pulse_rate', models.CharField(blank=True, help_text='e.g. 72 bpm', max_length=20)),
                ('temperature', models.CharField(blank=True, help_text='e.g. 98.4 F', max_length=20)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=1, help_text='Patient weight in kg', max_digits=5, null=True)),
                ('advice_diet', models.TextField(blank=True, help_text='Lifestyle, diet and recovery advice')),
                ('follow_up_date', models.DateField(blank=True, help_text='Recommended follow-up visit date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='appointments.appointment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(help_text='Brand or Generic Name (e.g. Paracetamol 650mg, Pantocid 40mg)', max_length=200)),
                ('dosage', models.CharField(help_text='e.g. 1 Tablet, 5ml, 1 Capsule', max_length=50)),
                ('frequency', models.CharField(choices=[('1-0-1 (Twice Daily After Food)', '1-0-1 (Twice Daily After Food)'), ('1-0-0 (Once Morning After Food)', '1-0-0 (Once Morning After Food)'), ('0-0-1 (Once Night After Food)', '0-0-1 (Once Night After Food)'), ('1-1-1 (Thrice Daily After Food)', '1-1-1 (Thrice Daily After Food)'), ('1-0-0 (Empty Stomach)', '1-0-0 (Empty Stomach / Before Food)'), ('SOS (As Needed)', 'SOS (As Needed / When Required)'), ('Custom', 'Custom Dosage Schedule')], default='1-0-1 (Twice Daily After Food)', max_length=100)),
                ('duration_days', models.PositiveIntegerField(default=5, help_text='Days to continue')),
                ('instructions', models.CharField(blank=True, help_text='Special instructions (e.g. take with warm water)', max_length=200)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='prescriptions.prescription')),
            ],
        ),
    ]
