# Generated by Django 6.1.1 on 2026-09-28 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(db_index=True)),
                ('appointment_time', models.TimeField()),
                ('appointment_type', models.CharField(choices=[('consultation', 'Initial Consultation'), ('follow_up', 'Follow-up Visit'), ('emergency', 'Emergency Walk-in'), ('report_review', 'Lab Report Review')], default='consultation', max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No-Show / Absent')], db_index=True, default='scheduled', max_length=20)),
                ('fee', models.DecimalField(decimal_places=2, default=400.0, max_digits=8)),
                ('reason', models.TextField(blank=True, help_text='Symptoms or purpose of visit')),
                ('doctor_notes', models.TextField(blank=True, help_text='Internal clinical notes')),
                ('reminder_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient')),
            ],
            options={
                'ordering': ['-appointment_date', '-appointment_time'],
                'indexes': [models.Index(fields=['appointment_date', 'status'], name='appointment_appoint_fb412a_idx'), models.Index(fields=['doctor', 'appointment_date'], name='appointment_doctor__4d4b79_idx')],
                'unique_together': {('doctor', 'appointment_date', 'appointment_time')},
            },
        ),
    ]
