# Generated by Django 6.1.1 on 2026-09-28 17:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='bi-droplet-half', help_text='Bootstrap icon name', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Lab Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LabOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, db_index=True, max_length=30, unique=True)),
                ('order_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending Sample Collection'), ('sample_collected', 'Sample Collected'), ('in_analysis', 'Under Testing / Analysis'), ('completed', 'Completed & Verified'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=30)),
                ('priority', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('stat', 'STAT (Emergency)')], default='routine', max_length=20)),
                ('sample_collected_at', models.DateTimeField(blank=True, null=True)),
                ('reported_at', models.DateTimeField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(blank=True, help_text='Referring Doctor (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_orders', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_orders', to='patients.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g., CBC, LFT, KFT, HBA1C', max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('sample_type', models.CharField(choices=[('Blood', 'Whole Blood / Serum / Plasma'), ('Urine', 'Urine Sample'), ('Stool', 'Stool Sample'), ('Swab', 'Throat / Nasal Swab'), ('Sputum', 'Sputum Sample'), ('Fluid', 'Body Fluids / CSF / Synovial'), ('Other', 'Other Sample Type')], default='Blood', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('turnaround_hours', models.PositiveIntegerField(default=4, help_text='Standard report delivery time in hours')),
                ('normal_range', models.CharField(blank=True, help_text='Standard Reference Interval', max_length=200)),
                ('unit', models.CharField(blank=True, help_text='Measurement unit (e.g. mg/dL, g/dL, %)', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Clinical significance and preparation instructions')),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='lab.labcategory')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LabOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_value', models.CharField(blank=True, max_length=200)),
                ('reference_range', models.CharField(blank=True, max_length=200)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('is_abnormal', models.BooleanField(default=False)),
                ('technician_remarks', models.TextField(blank=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='lab.laborder')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lab.labtest')),
            ],
        ),
    ]
