# Generated by Django 6.1.1 on 2026-09-28 17:59

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(choices=[('General Physician', 'General Physician & Internal Medicine'), ('Cardiologist', 'Cardiology & Heart Care'), ('Diabetologist', 'Diabetology & Endocrinology'), ('Pediatrician', 'Pediatrics & Child Health'), ('Gynecologist', 'Obstetrics & Gynecology'), ('Dermatologist', 'Dermatology & Skin Care'), ('Orthopedist', 'Orthopedics & Joint Care'), ('ENT Specialist', 'Ear, Nose & Throat (ENT)'), ('Pathologist', 'Pathology & Lab Diagnostics')], default='General Physician', max_length=100)),
                ('qualification', models.CharField(help_text='e.g., MBBS, MD (General Medicine), DNB', max_length=200)),
                ('experience_years', models.PositiveIntegerField(default=1)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=400.0, max_digits=8)),
                ('room_number', models.CharField(default='OPD-1', help_text='Consulting Room No.', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='doctors/')),
                ('bio', models.TextField(blank=True, help_text='Professional background and clinical focus')),
                ('available_days', models.CharField(default='Monday,Tuesday,Wednesday,Thursday,Friday,Saturday', help_text='Comma-separated days', max_length=100)),
                ('start_time', models.TimeField(default=datetime.time(9, 0), help_text='Consulting Start Time')),
                ('end_time', models.TimeField(default=datetime.time(18, 0), help_text='Consulting End Time')),
                ('slot_duration_minutes', models.PositiveIntegerField(default=15, help_text='Minutes per patient slot')),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['specialization', 'user__first_name'],
            },
        ),
    ]
