# Generated by Django 6.1.1 on 2026-09-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='end_time',
            field=models.TimeField(default='18:00:00', help_text='Consulting End Time'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='start_time',
            field=models.TimeField(default='09:00:00', help_text='Consulting Start Time'),
        ),
    ]
